// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
/// <reference types="node" />

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use globalThis to avoid needing Node type definitions for `process`
    url: (globalThis as any).process?.env["DATABASE_URL"]!,
  },
});
